---
- name: Setup joeyp stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variable
      include_vars: vars/vpc-output_vars

    - name: Import joeystack setup variable
      include_vars: vars/joeystacksetup

    - name: Create joeystack ec2 key
      ec2_key:
        name: joeykey
        region: "{{region}}"
      register: joeykey_out

    - name: Save priv key into file jokeypair.pem
      copy:
        content: "{{joeykey_out.key.private_key}}"
        dest: "./jokeypair.pem"
        mode: 0400
      when: joeykey_out.changed

    - name: Create security Group for Load Balancer
      ec2_group:
        name: joeypELB-sg
        description: Allow port 80 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: joeypELBsg_out

    - name: Create Security Group for Joeyp stack
      ec2_group:
        name: joeyp-sg
        description: Allow port 22 from  everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{joeypELBsg_out.group_id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}"
      register: joeypStackSG_out

    - name: Create Security Group with its own sg id
      ec2_group:
        name: joeyp-sg
        description: Allow port 22 from  everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{joeypStackSG_out.group_id}}"



    - name: Creating Nginx web01
      ec2:
        key_name: joeykey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{nginx_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "web01"
          Project: joeyp
          Owner: DevOps Team
        exact_count: 1
        count_tag:
          Name: "web01"
          Project: joeyp
          Owner: DevOps Team
        group_id: "{{joeypStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: web01_out

    - name: Creating tomcat app01
      ec2:
        key_name: joeykey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{tomcat_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "app01"
          Project: joeyp
          Owner: DevOps Team
        exact_count: 1
        count_tag:
          Name: "app01"
          Project: joeyp
          Owner: DevOps Team
        group_id: "{{joeypStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: app01_out

    - name: Creating memcache mc01
      ec2:
        key_name: joeykey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{memcache_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "mc01"
          Project: joeyp
          Owner: DevOps Team
        exact_count: 1
        count_tag:
          Name: "mc01"
          Project: joeyp
          Owner: DevOps Team
        group_id: "{{joeypStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: mc01_out

    - name: Creating RabbitMQ rmq01
      ec2:
        key_name: joeykey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{rmq_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "rmq01"
          Project: joeyp
          Owner: DevOps Team
        exact_count: 1
        count_tag:
          Name: "rmq01"
          Project: joeyp
          Owner: DevOps Team
        group_id: "{{joeypStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: rmq01_out

    - name: Creating Mysql db01
      ec2:
        key_name: joeykey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{mysql_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "db01"
          Project: joeyp
          Owner: DevOps Team
        exact_count: 1
        count_tag:
          Name: "db01"
          Project: joeyp
          Owner: DevOps Team
        group_id: "{{joeypStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: db01_out

    - debug:
        var: db01_out.tagged_instances[0].id

    - local_action:
        module: ec2_elb_lb
        name: "joeyp-elb"
        region: "{{region}}"
        state: present
        instance_ids:
          - "{{ web01_out.tagged_instances[0].id }}"
        purge_instance_ids: true
        security_group_ids: "{{ joeypELBsg_out.group_id }}"
        subnets:
          - "{{ pubsub1id }}"
          - "{{ pubsub2id }}"
          - "{{ pubsub3id }}"
        listeners:
          - protocol: http # options are http, https, ssl, tcp
            load_balancer_port: 80
            instance_port: 80

    - name: Insert/Update Hosts IP & Name in file provision-stack/group_vars/hostsip
      blockinfile:
        path: provision-stack/group_vars/hostsip
        block: |
          web01_ip: {{ web01_out.tagged_instances[0].private_ip }}
          app01_ip: {{ app01_out.tagged_instances[0].private_ip }}
          rmq01_ip: {{ rmq01_out.tagged_instances[0].private_ip }}
          mc01_ip: {{ mc01_out.tagged_instances[0].private_ip }}
          db01_ip: {{ db01_out.tagged_instances[0].private_ip }}
    - name: Copy login key to provision_stack directory
      copy:
        src: jokeypair.pem
        dest: provision-stack/jokeypair.pem
        mode: '0400'

    - name: Insert/Update Inventory file provision-stack/inventory-vpro
      blockinfile:
        path: provision-stack/inventory-vpro
        block: |
          web01 ansible_host={{ web01_out.tagged_instances[0].private_ip }}
          app01 ansible_host={{ app01_out.tagged_instances[0].private_ip }}
          rmq01 ansible_host={{ rmq01_out.tagged_instances[0].private_ip }}
          mc01 ansible_host={{ mc01_out.tagged_instances[0].private_ip }}
          db01 ansible_host={{ db01_out.tagged_instances[0].private_ip }}
          cntl ansible_host=127.0.0.1 ansible_connection=local
          [websrvgrp]
          web01
          [appsrvgrp]
          app01
          [rmqsrvgrp]
          rmq01
          [mcsrvgrp]
          mc01
          [dbsrvgrp]
          db01
          [control]
          cntl
          [stack_inst:children]
          websrvgrp
          appsrvgrp
          rmqsrvgrp
          mcsrvgrp
          dbsrvgrp
          [stack_inst:vars]
          ansible_user=ubuntu
          ansible_ssh_private_key_file=jokeypair.pem
          ansible_python_interpreter=/usr/bin/python3